language: python
python:
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
before_script: 
  - mysqladmin create gpsi -u travis -p
  - python manage.py syncdb
  - python manage.py migrate
  - cd scripts
  - python creategroups.py
  - cd ..
# command to run tests, e.g. python setup.py test
script:  python manage.py test schedule